/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package surat_km;

import java.awt.Color;
import java.awt.Font;
import com.mysql.jdbc.Statement;
import java.sql.*;
import javax.swing.JOptionPane;
import surat_km.koneksi;
import javax.swing.table.DefaultTableModel;
import java.text.SimpleDateFormat;

/**
 *
 * @author Fasih
 */
public class surat_masuk extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    Connection con;
    java.sql.Statement stat;
    ResultSet rs;
    String sql;
    int mouseX;
    int mouseY;
    public surat_masuk() {
        initComponents();
        koneksi DB = new koneksi();
        DB.Connection();
        con = DB.con;
        stat = DB.stm;
      jTable1.getTableHeader().setFont(new Font("Montsrat ExtraBold",Font.BOLD,12));
      jTable1.getTableHeader().setOpaque(false);
      jTable1.getTableHeader().setBackground(new Color(54,131,158));
      jTable1.getTableHeader().setForeground(new Color(255,255,255));
      jTable1.setRowHeight(25);
      datatable();
    }
public void datatable(){
    DefaultTableModel tbl = new DefaultTableModel();
    
    tbl.addColumn("No_Surat");
    tbl.addColumn("Tanggal_Surat");
    tbl.addColumn("Terima_Dari");
    tbl.addColumn("Isi_Prihal");
    tbl.addColumn("Lampiran");
    tbl.addColumn("Keterangan");
    jTable1.setModel(tbl);
    try {
        sql = "select * from surat_masuk";
        rs=stat.executeQuery(sql);
        while(rs.next()){
            tbl.addRow(new Object[]{
            rs.getString("no_surat"),
            rs.getString("tanggal_terima"),
            rs.getString("terima_dari"),
            rs.getString("isi_prihal"),
            rs.getString("lampiran"),
            rs.getString("keterangan"),
            
        });
            jTable1.setModel(tbl);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "salah"+e);
    }
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        minimize = new javax.swing.JLabel();
        close = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        dragbar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        tgl = new javax.swing.JTextField();
        terima = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        isi = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        lampir = new javax.swing.JTextArea();
        ket = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/Asset 15.png"))); // NOI18N
        minimize.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 7, 60, 40));

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/Asset 14.png"))); // NOI18N
        close.setOpaque(true);
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(1207, 10, 50, 40));

        jPanel1.setBackground(new java.awt.Color(240, 42, 56));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(240, 75, 66));
        jLabel5.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Logout");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 10, 80, 30));

        dragbar.setBackground(new java.awt.Color(255, 0, 0));
        dragbar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                dragbarMouseDragged(evt);
            }
        });
        dragbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dragbarMousePressed(evt);
            }
        });
        getContentPane().add(dragbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 1280, 52));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 131, 158));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_login/Asset 16.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jPanel5.setBackground(new java.awt.Color(54, 131, 158));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_dashboard/Asset 36.png"))); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 4, 90, 50));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 306, 60));

        jPanel6.setBackground(new java.awt.Color(27, 147, 169));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_dashboard/Asset 34.png"))); // NOI18N
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 2, -1, 60));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 306, 60));

        jPanel7.setBackground(new java.awt.Color(54, 131, 158));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_dashboard/Asset 35.png"))); // NOI18N
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 2, -1, 60));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 306, 60));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 306, 720));

        jLabel7.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel7.setText("No Surat");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jLabel8.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel8.setText("Tanggal Terima");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel9.setText("terima dari");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel10.setText("Isi/Prihal");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel11.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel11.setText("Lampiran");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("Montserrat Medium", 0, 18)); // NOI18N
        jLabel12.setText("Keterangan");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 430, -1, -1));
        jPanel3.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, 230, -1));
        jPanel3.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 230, -1));
        jPanel3.add(terima, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 230, -1));

        isi.setColumns(20);
        isi.setRows(5);
        jScrollPane1.setViewportView(isi);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, 230, -1));

        lampir.setColumns(20);
        lampir.setRows(5);
        jScrollPane2.setViewportView(lampir);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 230, -1));
        jPanel3.add(ket, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, 230, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 70, 100, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Batal");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 100, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No_Surat", "Tanggal_Surat", "Terima_Dari", "Isi_Prihal", "Lampiran", "Keterangan"
            }
        ));
        jTable1.setFocusable(false);
        jTable1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable1.setRowHeight(25);
        jTable1.setSelectionBackground(new java.awt.Color(240, 75, 66));
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 470, 910, 210));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cari");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 100, 30));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Hapus");
        jButton4.setToolTipText("");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 190, 100, 30));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Edit");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 100, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(1);
    }//GEN-LAST:event_minimizeMouseClicked

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeMouseClicked

    private void dragbarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragbarMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_dragbarMousePressed

    private void dragbarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dragbarMouseDragged
        int kordinatX = evt.getXOnScreen();
        int kordinatY = evt.getYOnScreen();
        this.setLocation(kordinatX - mouseX, kordinatY - mouseY);
    }//GEN-LAST:event_dragbarMouseDragged

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        login lg = new login();
        lg.setVisible(true);
        lg.pack();
        lg.setLocationRelativeTo(null);
        lg.setDefaultCloseOperation(login.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        Home hm = new Home();
        hm.setVisible(true);
        hm.pack();
        hm.setLocationRelativeTo(null);
        hm.setDefaultCloseOperation(Home.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        jPanel5.setBackground(new Color(27,147,169));
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        surat_masuk sm = new surat_masuk();
        sm.setVisible(true);
        sm.pack();
        sm.setLocationRelativeTo(null);
        sm.setDefaultCloseOperation(surat_masuk.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        jPanel6.setBackground(new Color(27,147,169));
    }//GEN-LAST:event_jPanel6MousePressed

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
       surat_keluar sk = new surat_keluar();
        sk.setVisible(true);
        sk.pack();
        sk.setLocationRelativeTo(null);
        sk.setDefaultCloseOperation(surat_keluar.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        jPanel7.setBackground(new Color(27,147,169));
    }//GEN-LAST:event_jPanel7MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String no_surat = no.getText();
        String tanggal_terima = tgl.getText();
        String terima_dari = terima.getText();
        String isi_prihal = isi.getText();
        String lampiran = lampir.getText();
        String keterangan = ket.getText();
        try {
            
            sql= "INSERT INTO surat_masuk VALUES('"+ no_surat +"','"+ tanggal_terima +"','"+ terima_dari +"','"+ isi_prihal +"','"+ lampiran +"','"+ keterangan +"');";
            stat.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(rootPane, "Data berhasil di simpan");
            
            no.setText("");
            tgl.setText("");
            terima.setText("");
            isi.setText("");
            lampir.setText("");
            ket.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Data gagal di simpan"+e);
        }
        datatable();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String no_surat = no.getText();
       
        try {
            sql="delete from surat_masuk where no_surat='"+ no_surat +"';";
            int pesan = JOptionPane.showConfirmDialog(null, "Yakin Data akan di hapus?","Konfirmasi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if (pesan==JOptionPane.YES_OPTION) {
                if (stat.executeUpdate(sql)==1) {
                    
                } else {
                    JOptionPane.showMessageDialog(null, "Data Gagal di hapus");
                }
            }
            no.setText("");
            tgl.setText("");
            terima.setText("");
            isi.setText("");
            lampir.setText("");
            ket.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data gagal di hapus"+e);
        }
        datatable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            no.setText("");
            tgl.setText("");
            terima.setText("");
            isi.setText("");
            lampir.setText("");
            ket.setText("");
            
            datatable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            sql="select * from surat_masuk where no_surat='"+ no.getText() +"' OR tanggal_terima='"+ tgl.getText() +"' OR terima_dari='"+ terima.getText() +"' ";
            rs=stat.executeQuery(sql);
            DefaultTableModel tbl = new DefaultTableModel();
            tbl.addColumn("No_Surat");
            tbl.addColumn("Tanggal_Surat");
            tbl.addColumn("Terima_Dari");
            tbl.addColumn("Isi_Prihal");
            tbl.addColumn("Lampiran");
            tbl.addColumn("Keterangan");
            
            jTable1.setModel(tbl);
            
            while (rs.next()) {
                tbl.addRow(new Object[]{
                    rs.getString("no_surat"),
                    rs.getString("tanggal_terima"),
                    rs.getString("terima_dari"),
                    rs.getString("isi_prihal"),
                    rs.getString("lampiran"),
                    rs.getString("keterangan"),
                });
                jTable1.setModel(tbl);
                no.setText(rs.getString("no_surat"));
                tgl.setText(rs.getString("tanggal_terima"));
                terima.setText(rs.getString("terima_dari"));
                isi.setText(rs.getString("isi_prihal"));
                lampir.setText(rs.getString("lampiran"));
                ket.setText(rs.getString("keterangan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "SAlah"+e);
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         // menampilkan data kedalam form pengisian:
        int baris = jTable1.rowAtPoint(evt.getPoint());
        String no_surat =jTable1.getValueAt(baris, 1).toString();
        no.setText(no_surat);
        String tgl_surat = jTable1.getValueAt(baris,2).toString();
        tgl.setText(tgl_surat);
 
        String terima_dri = jTable1.getValueAt(baris, 3).toString();
        terima.setText(terima_dri);
        String isi_prl=jTable1.getValueAt(baris, 4).toString();
        isi.setText(isi_prl);
        String lampiran = jTable1.getValueAt(baris, 5).toString();
        lampir.setText(lampiran);
        String keterangan = jTable1.getValueAt(baris, 5).toString();
        ket.setText(keterangan);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try {
            sql ="UPDATE surat_masuk SET no_surat = '"+no.getText()+"', tanggal_terima = '"+tgl.getText()+"', terima_dari = '"+terima.getText()+"',isi_prihal= '"+isi.getText()+"',lampiran= '"+lampir.getText()+"',keterangan = '"+ket.getText()+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "data berhasil di edit");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Perubahan Data Gagal"+e);
        }
            no.setText("");
            tgl.setText("");
            terima.setText("");
            isi.setText("");
            lampir.setText("");
            ket.setText("");
        datatable();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line argumentdragbar*/
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(surat_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(surat_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(surat_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(surat_masuk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new surat_masuk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel dragbar;
    private javax.swing.JTextArea isi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField ket;
    private javax.swing.JTextArea lampir;
    private javax.swing.JLabel minimize;
    private javax.swing.JTextField no;
    private javax.swing.JTextField terima;
    private javax.swing.JTextField tgl;
    // End of variables declaration//GEN-END:variables
}
